- name: "Objektpflege"
  desc: "Sie besitzen Immobilien, können aber nicht immer vor Ort sein? Wir übernehmen sämtliche Hausmeistertätigkeiten."
- name: "Rasenpflege"
  desc: "20 oder 1.000 m2? Privat oder gewerblich? Kein Problem! Wir mähen, düngen und bewässern jede Rasenfläche und sorgen für ein gesundes Grün in Ihrem Außenbereich."
- name: "Rollrasen"
  desc: "Wer möchte keinen satten und grünen Rasen ohne Moos und kahle Stellen. Wir verlegen fachgerecht Ihren neuen Rasen."
- name: "Dauerpflege"
  desc: "Einmal besprochen, keine Sorgen mehr! Wir pflegen Ihren Garten in regelmäßigen Abständen, ob 2 wöchentlich, monatlich oder vierteljährlich und binden Sie dabei nicht an lange Vertragslaufzeiten. Unsere Verträge sind monatlich kündbar."
- name: "Bepflanzung"
  desc: "Bodendecker, Kletterpflanzen, Sträucher, Gehölze, Stauden und Blühpflanzen. Die Welt der Pflanzen bietet eine umfangreiche Auswahl an Gestaltungsmöglichkeiten für Ihren Garten. Wir beraten Sie gerne und setzen Ihre Vorstellungen um."
- name: "Automatisierung Ihres Gartens"
  desc: "Berufstätig und trotzdem einen schönen und gepflegten Rasen? Ja das geht! Auch ohne die Dauerpflege eines Gärtners. Wir sind Ihr kompetenter Ansprechpartner in Sachen Mähroboter und Bewässerungssysteme."